### ISSUE TITLE
Splash Screen and Favicon use the UI5 Logo

### ISSUE THREAD

**Issue by gregorwolf** [marianfoo/bestofcapjs-website#2]
Hi @marianfoo,

thank you for this great initiative. I'm sure you aware that the Splash Screen and Favicon use the UI5 right now. Maybe @renejeglinsky can help with the needed images.

CU
Gregor

**Comment by marianfoo** [comment]
Yes, I agree.
Would be nice to have some svg images.

**Comment by marianfoo** [comment]
Any progress here @gregorwolf ?

**Comment by renejeglinsky** [comment]
Would you want to use the CAP Logo? I think I misunderstood the issue back in January

**Comment by marianfoo** [comment]
Hi @renejeglinsky ,

yes, currently i use the ui5 logo as svg.
Would be great to have a CAP Logo light/dark theme to replace it with.

Here is the ui5 logo:
https://github.com/marianfoo/bestofcapjs-website/blob/main/src/img/O_UI5_V.svg

**Comment by renejeglinsky** [comment]
Alright, I'll get back to you on this :)

**Comment by renejeglinsky** [comment]
Hi @marianfoo ,

according to the [Apache 2.0 License](https://github.com/cap-js/docs/blob/main/.reuse/dep5), you're allowed to use the [CAP Logo](https://github.com/cap-js/docs/blob/main/public/assets/logos/cap.svg#L0-L1) when mentioning the copyright and license.

All the best,
René

**Comment by marianfoo** [comment]
Thanks @renejeglinsky !
i added it
